version: '3.8'
services: 

  db:
    image: postgres:13.3
    user: root
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data_pg:/var/lib/postgresql/data

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  workers:
    build: ./workers
    ports: 
        - 8081:8081
    # command: python worker.py
    env_file:
      - .env
    depends_on:
        - kafka
        - db

  app: 
      build: ./app
      ports: 
        - 8080:8080
      env_file:
        - .env
      depends_on:
      - db
      - kafka

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - ./cache:/data