version: '3.8'
services: 
  db:
      image: postgres:13.3
      user: root
      restart: always
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: E5rG7tY3fH
        POSTGRES_DB: W9sV6cL2dX
      volumes:
        - ./data_pg:/var/lib/postgresql/data

  app: 
      build: ./app
      ports: 
        - 8080:8080
      depends_on:
      - db

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - ./cache:/data
