version: '3.8'
services: 
  app: 
      build: ./app
      ports: 
        - 8080:8080
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
