version: '3.8'
services: 
  app: 
      build: ./app
      ports: 
        - 8080:8080
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - cache:/data
  db:
      image: postgres:14.1-alpine
      restart: always
      environment:
        - POSTGRES_USER="${POSTGRES_USER}"
        - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
      ports:
        - '5438:5432'
      volumes: 
        - db:/var/lib/postgresql/data
        # # copy the sql script to create tables
        # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  cache:
    driver: local
  db:
    driver: local
