version: '1.0'
services: 
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER="${POSTGRES_USER}"
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
    ports:
      - '5432:5432'
      #- '5438:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  worker:
    build: ./worker
    command: python worker.py
    depends_on:
      - kafka
      - db
  app: 
      build: ./app
      ports: 
        - 8080:8080
      depends_on:
      - db
      - kafka
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
  db:
    driver: local